# This workflows will build a Java project with Maven, and cache/restore any dependencies to improve the workflows execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflows uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21 and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle' # update to 'temurin' when released
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify --file server/pom.xml

      - name: Test Reports
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Reports
          path: server/target/failsafe-reports/*Spec.xml
          reporter: java-junit
          fail-on-error: true

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: server/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 90
          min-coverage-changed-files: 70
